[twitter]
# Enter your secrets here. See README.md for more info.
consumer_key = '1481436970303827976-etzV7VmtmOxL3lhiyDKPgGJXigTjhN'
consumer_secret = 'pnVavZehJtKS5fq5LrBn6ylnHpjaVfN5djg2jSIg7652K'
